import { MovieCodegenType } from 'react-native-movies-list';

function transformApiResponse(apiResponse: any): MovieCodegenType[] {
    return apiResponse.map(movie => {
      return {
        id: movie.id,
        title: movie.title,
        url: `https://image.tmdb.org/t/p/w500${movie.backdrop_path}`,
        movieDescription: movie.overview,
        rating: movie.vote_average,
      };
    });
  }



  const data = [
    {
        'backdrop_path': '/rn8Sg6C8aWKRWdqY4hIpmOaiuqS.jpg',
        'id': 710295,
        'title': 'Wolf Man',
        'original_title': 'Wolf Man',
        'overview': "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
        'poster_path': '/vtdEHG1j07PqLlVyhKNZRHTPKGt.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            27,
            53,
        ],
        'popularity': 776.426,
        'release_date': '2025-01-15',
        'video': false,
        'vote_average': 6.3,
        'vote_count': 198,
    },
    {
        'backdrop_path': '/h7r6LZ32dgLwtwSW3CxoWIYD9pr.jpg',
        'id': 426063,
        'title': 'Nosferatu',
        'original_title': 'Nosferatu',
        'overview': 'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
        'poster_path': '/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            27,
            14,
        ],
        'popularity': 859.647,
        'release_date': '2024-12-25',
        'video': false,
        'vote_average': 6.651,
        'vote_count': 1929,
    },
    {
        'backdrop_path': '/uKb22E0nlzr914bA9KyA5CVCOlV.jpg',
        'id': 402431,
        'title': 'Wicked',
        'original_title': 'Wicked',
        'overview': "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
        'poster_path': '/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            18,
            10749,
            14,
        ],
        'popularity': 515.337,
        'release_date': '2024-11-20',
        'video': false,
        'vote_average': 6.909,
        'vote_count': 1667,
    },
    {
        'backdrop_path': '/hctfNoMpQGfn3VXdBYb9p0P5bT5.jpg',
        'id': 1097549,
        'title': 'Babygirl',
        'original_title': 'Babygirl',
        'overview': 'A high-powered CEO puts her career and family on the line when she begins a torrid affair with her much younger intern.',
        'poster_path': '/A8HbTd0FemZyFCh5qvJFpHGiwF8.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            18,
        ],
        'popularity': 860.842,
        'release_date': '2024-12-25',
        'video': false,
        'vote_average': 5.764,
        'vote_count': 383,
    },
    {
        'backdrop_path': '/7uGoDVlmB7JT2JrQ6fvNPoQeAo0.jpg',
        'id': 980477,
        'title': 'Ne Zha 2',
        'original_title': '哪吒之魔童闹海',
        'overview': 'After the tribulation, although the souls of Ne Zha and Ao Bing were preserved, their physical bodies would soon be completely destroyed.Tai Yi Zhen Ren plans to use the Seven Colored Lotus to reshape their physical bodies. But in the process of reshaping their physical bodies, they encountered numerous difficulties. Where will the fate of Ne Zha and Ao Bing go?',
        'poster_path': '/ztVAaQC6dEO49EQveGxpsH8P6BW.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'zh',
        'genre_ids': [
            16,
            14,
            12,
        ],
        'popularity': 174.568,
        'release_date': '2025-01-29',
        'video': false,
        'vote_average': 7.9,
        'vote_count': 34,
    },
    {
        'backdrop_path': '/zDn58IGLtNxDrEnEkO7JM814HiF.jpg',
        'id': 636279,
        'title': 'Bogotá: City of the Lost',
        'original_title': '보고타: 마지막 기회의 땅',
        'overview': 'After moving to Bogotá for a chance at a better life, a young Korean man rises through the Colombian black market — risking peril for a shot at success.',
        'poster_path': '/p1WPGGPVHHVJwTjmUaCsbTNATgn.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'ko',
        'genre_ids': [
            53,
            80,
            18,
        ],
        'popularity': 127.333,
        'release_date': '2024-12-31',
        'video': false,
        'vote_average': 7.4,
        'vote_count': 41,
    },
    {
        'backdrop_path': '/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg',
        'id': 1241982,
        'title': 'Moana 2',
        'original_title': 'Moana 2',
        'overview': "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
        'poster_path': '/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            16,
            12,
            10751,
            35,
        ],
        'popularity': 1478.141,
        'release_date': '2024-11-21',
        'video': false,
        'vote_average': 7.2,
        'vote_count': 1336,
    },
    {
        'backdrop_path': '/hZSOdJFLECTBO8PpYkVI3rPsY2D.jpg',
        'id': 1212142,
        'title': 'Kinda Pregnant',
        'original_title': 'Kinda Pregnant',
        'overview': "When Lainy's plan to settle down and start a family falls apart, she puts on a fake baby bump, tells a lie — and accidentally falls for her dream guy.",
        'poster_path': '/k2Lq3rCJ7P9gk5Df9of9kqr9IJM.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            35,
            10749,
        ],
        'popularity': 176.007,
        'release_date': '2025-02-04',
        'video': false,
        'vote_average': 5.4,
        'vote_count': 49,
    },
    {
        'backdrop_path': '/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg',
        'id': 939243,
        'title': 'Sonic the Hedgehog 3',
        'original_title': 'Sonic the Hedgehog 3',
        'overview': 'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
        'poster_path': '/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            28,
            878,
            35,
            10751,
        ],
        'popularity': 3180.548,
        'release_date': '2024-12-19',
        'video': false,
        'vote_average': 7.779,
        'vote_count': 1587,
    },
    {
        'backdrop_path': '/aMbKYfaexixvsBZKc5whYO7yibR.jpg',
        'id': 1082195,
        'title': 'The Order',
        'original_title': 'The Order',
        'overview': 'A string of violent robberies in the Pacific Northwest leads veteran FBI agent Terry Husk into a white supremacist plot to overthrow the federal government.',
        'poster_path': '/vxB2cApyk0bImBfMHr0oJUdeGdK.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            53,
            80,
            18,
        ],
        'popularity': 76.994,
        'release_date': '2024-12-05',
        'video': false,
        'vote_average': 6.7,
        'vote_count': 193,
    },
    {
        'backdrop_path': '/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg',
        'id': 1064213,
        'title': 'Anora',
        'original_title': 'Anora',
        'overview': 'A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.',
        'poster_path': '/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            18,
            35,
            10749,
        ],
        'popularity': 457.308,
        'release_date': '2024-10-14',
        'video': false,
        'vote_average': 7.1,
        'vote_count': 953,
    },
    {
        'backdrop_path': '/nEH7XUCeWsEuJtGgWUVUl6MEQW0.jpg',
        'id': 1211472,
        'title': 'September 5',
        'original_title': 'September 5',
        'overview': 'During the 1972 Munich Olympics, an American sports broadcasting crew finds itself thrust into covering the hostage crisis involving Israeli athletes.',
        'poster_path': '/3kcQOLwYKGPwyjiynFsvP8vHvRn.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            18,
            53,
            36,
        ],
        'popularity': 171.942,
        'release_date': '2024-11-07',
        'video': false,
        'vote_average': 6.724,
        'vote_count': 49,
    },
    {
        'backdrop_path': '/eGK2JJO1ZeoabWThHmC9IjUTmfP.jpg',
        'id': 615453,
        'title': 'Ne Zha',
        'original_title': '哪吒之魔童降世',
        'overview': 'The Primus extracts a Mixed Yuan Bead into a Spirit Seed and a Demon Pill. The Spirit Seed can be reincarnated as a human to help King Zhou establish a new dynasty, whereas the Demon Pill will create a devil threatening humanity. Ne Zha is the one who is destined to be the hero, but instead he becomes a devil incarnate, because the Spirit Seed and a Demon Pill are switched.',
        'poster_path': '/phM9bb6s9c60LA8qwsdk7U1N2cS.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'zh',
        'genre_ids': [
            16,
            14,
            12,
        ],
        'popularity': 159.061,
        'release_date': '2019-07-26',
        'video': false,
        'vote_average': 7.9,
        'vote_count': 418,
    },
    {
        'backdrop_path': '/8dqZsevb5E8x29OFyr1neSp7bc9.jpg',
        'id': 933260,
        'title': 'The Substance',
        'original_title': 'The Substance',
        'overview': 'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
        'poster_path': '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            27,
            878,
            35,
        ],
        'popularity': 630.258,
        'release_date': '2024-09-07',
        'video': false,
        'vote_average': 7.1,
        'vote_count': 3692,
    },
    {
        'backdrop_path': '/sc1abgWNXc29wSBaerrjGBih06l.jpg',
        'id': 1084199,
        'title': 'Companion',
        'original_title': 'Companion',
        'overview': 'During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.',
        'poster_path': '/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            878,
            27,
            35,
        ],
        'popularity': 354.637,
        'release_date': '2025-01-22',
        'video': false,
        'vote_average': 7.166,
        'vote_count': 178,
    },
    {
        'backdrop_path': '/9tIgF5Ht9ndLJEwv2e6TZrExMKw.jpg',
        'id': 974950,
        'title': 'Emilia Pérez',
        'original_title': 'Emilia Pérez',
        'overview': 'Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.',
        'poster_path': '/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'fr',
        'genre_ids': [
            18,
            53,
        ],
        'popularity': 234.637,
        'release_date': '2024-08-21',
        'video': false,
        'vote_average': 7.2,
        'vote_count': 1149,
    },
    {
        'backdrop_path': '/mKIxSo3p1QKlsdegcOwapcbiV74.jpg',
        'id': 604685,
        'title': 'Den of Thieves 2: Pantera',
        'original_title': 'Den of Thieves 2: Pantera',
        'overview': "Big Nick is back on the hunt in Europe and closing in on Donnie, who is embroiled in the treacherous and unpredictable world of diamond thieves and the infamous Panther mafia, as they plot a massive heist of the world's largest diamond exchange.",
        'poster_path': '/zLHq7fQA3xpck5UIHcRYgip5pQD.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            28,
            80,
            53,
        ],
        'popularity': 329.231,
        'release_date': '2025-01-08',
        'video': false,
        'vote_average': 6.7,
        'vote_count': 189,
    },
    {
        'backdrop_path': '/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg',
        'id': 993710,
        'title': 'Back in Action',
        'original_title': 'Back in Action',
        'overview': 'Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.',
        'poster_path': '/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            28,
            35,
        ],
        'popularity': 1238.258,
        'release_date': '2025-01-15',
        'video': false,
        'vote_average': 6.638,
        'vote_count': 817,
    },
    {
        'backdrop_path': '/xaNBpBkONtupAVJqQBIW5EZa7xi.jpg',
        'id': 996821,
        'title': "You're Cordially Invited",
        'original_title': "You're Cordially Invited",
        'overview': "When two weddings are accidentally booked on the same day at the same venue, each bridal party is challenged with preserving their family's special moment while making the most of the unanticipated tight quarters. In a hilarious battle of determination and grit, the father of the bride and sister of the other bride chaotically go head-to-head as they stop at nothing to uphold an unforgettable celebration for their loved ones.",
        'poster_path': '/muXnwAdVdEEktto0NBNMyqK3uQH.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'en',
        'genre_ids': [
            35,
        ],
        'popularity': 388.354,
        'release_date': '2025-01-29',
        'video': false,
        'vote_average': 5.9,
        'vote_count': 199,
    },
    {
        'backdrop_path': '/bZsATFS6wg6L45ele7Ve4ogGkUT.jpg',
        'id': 60898,
        'title': 'Erotic Ghost Story',
        'original_title': '聊齋艷譚',
        'overview': "Three vixens have meditated for 1,000 years to able to shed their animal natures and become human. For the final month of their rigors, they have moved near a village where women pray to a god of fertility. One sister visits the god's temple and thinks lustful thoughts. As she leaves, a priest confronts her, warning of dire consequences and of demons that will try to stop the vixens' transformation. Soon, the youngest sister saves a poor scholar from bandits and becomes enamored of him. Each sister visits him, and before long, the youth has made love to all three. After they invite him to stay with them, the playfulness takes a scary turn. Where can they turn for help?",
        'poster_path': '/fTUCwsxVoLFuodAtlL6aITP1B45.jpg',
        'media_type': 'movie',
        'adult': false,
        'original_language': 'cn',
        'genre_ids': [
            14,
            18,
            27,
        ],
        'popularity': 68.03,
        'release_date': '1990-05-19',
        'video': false,
        'vote_average': 6.2,
        'vote_count': 81,
    },
];

const fakeMovies = transformApiResponse(data);
export default fakeMovies;
